# Use oven/bun:alpine as the base image for all stages
FROM oven/bun:alpine AS base
WORKDIR /app
RUN apk add --no-cache python3 g++ make git

# ========================
# Build ytmusic-api
# ========================
FROM node:22.4.1-alpine AS ytmusic-api-builder
WORKDIR /builder
RUN apk add --no-cache git
RUN git clone --depth=1 https://github.com/ponlponl123/ts-npm-ytmusic-api /builder/ts-npm-ytmusic-api \
    && cd /builder/ts-npm-ytmusic-api \
    && npm install \
    && npm install -g tsup \
    && npm run build

# ========================
# Install Dependencies & Build Project
# ========================
FROM node:22.4.1-alpine AS builder
WORKDIR /pona-builder
RUN apk add --no-cache python3 make g++
COPY package.json package-lock.json ./
RUN npm install --production
COPY . . 

# Copy ytmusic-api build
COPY --from=ytmusic-api-builder /builder/ts-npm-ytmusic-api ./node_modules/ytmusic-api

# ========================
# Build the App with Bun
# ========================
FROM base AS bun-builder
WORKDIR /pona-builder
RUN apk add --no-cache npm
COPY --from=builder /pona-builder/ ./
RUN bun install tsup \
    && bun bun:build

# ========================
# Final Image (Minimal)
# ========================
FROM base AS runner
WORKDIR /pona
ENV NODE_ENV=production

# Copy only necessary files
COPY --from=bun-builder /pona-builder/dist ./dist
COPY --from=bun-builder /pona-builder/public ./dist/public
COPY --from=bun-builder /pona-builder/package.json ./package.json

EXPOSE 3000
ENV PORT=3000

CMD ["bun", "bun:start-reg-shard"]