FROM node:22.4.1-alpine AS base
RUN apk add python3 g++ make git

FROM base AS ytmusic-api-builder
WORKDIR /builder

# Clone the GitHub repository and build the library
RUN git clone https://github.com/ponlponl123/ts-npm-ytmusic-api
WORKDIR /builder/ts-npm-ytmusic-api

# Install dependencies and build the library
RUN npm install
RUN npm run build

# Set up the app and build the project
FROM base AS builder
WORKDIR /pona
ENV NODE_ENV=production
COPY package.json package-lock.json ./
RUN npm install
COPY . .
COPY --from=ytmusic-api-builder /builder/ts-npm-ytmusic-api ./node_modules/ytmusic-api

FROM oven/bun:alpine AS pona
WORKDIR /pona
COPY --from=builder /pona .
EXPOSE 3000
ENV PORT=3000
CMD ["bun", "src/index.ts"]